<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PolandSeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->getData();

        foreach ($data as $wojewodztwo => $powiaty) {
            $wojewodztwoId = DB::table('wojewodztwa')->insertGetId([
                'nazwa' => $wojewodztwo,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            foreach ($powiaty as $powiat => $gminy) {
                $powiatId = DB::table('powiaty')->insertGetId([
                    'wojewodztwo_id' => $wojewodztwoId,
                    'nazwa' => $powiat,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                foreach ($gminy as $gmina) {
                    DB::table('gminy')->insert([
                        'powiat_id' => $powiatId,
                        'nazwa' => $gmina,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }
    }

    private function getData(): array
    {
        return [
            "Dolnośląskie" => [
                "Bolesławiecki" => ["Bolesławiec", "Gromadka", "Nowogrodziec", "Osiecznica", "Warta Bolesławiecka"],
                "Dzierżoniowski" => ["Bielawa", "Dzierżoniów", "Niemcza", "Pieszyce", "Piława Górna", "Łagiewniki"],
                "Głogowski" => ["Głogów", "Jerzmanowa", "Kotla", "Pęcław", "Żukowice"],
                "Górowski" => ["Góra", "Jemielno", "Niechlów", "Wąsosz"],
                "Jaworski" => ["Bolków", "Jawor", "Męcinka", "Mściwojów", "Paszowice", "Wądroże Wielkie"],
                "Karkonoski" => ["Janowice Wielkie", "Jeżów Sudecki", "Karpacz", "Kowary", "Mysłakowice", "Piechowice", "Podgórzyn", "Stara Kamienica", "Szklarska Poręba"],
                "Kamiennogórski" => ["Kamienna Góra", "Lubawka", "Marciszów"],
                "Kłodzki" => ["Bystrzyca Kłodzka", "Duszniki-Zdrój", "Kudowa-Zdrój", "Kłodzko", "Lewin Kłodzki", "Lądek-Zdrój", "Międzylesie", "Nowa Ruda", "Polanica-Zdrój", "Radków", "Stronie Śląskie", "Szczytna"],
                "Legnicki" => ["Chojnów", "Krotoszyce", "Kunice", "Legnickie Pole", "Miłkowice", "Prochowice", "Ruja"],
                "Lubański" => ["Leśna", "Lubań", "Olszyna", "Platerówka", "Siekierczyn", "Świeradów-Zdrój"],
                "Lubiński" => ["Lubin", "Rudna", "Ścinawa"],
                "Lwówecki" => ["Gryfów Śląski", "Lubomierz", "Lwówek Śląski", "Mirsk", "Wleń"],
                "Milicki" => ["Cieszków", "Krośnice", "Milicz"],
                "Oleśnicki" => ["Bierutów", "Dobroszyce", "Dziadowa Kłoda", "Międzybórz", "Oleśnica", "Syców", "Twardogóra"],
                "Oławski" => ["Domaniów", "Jelcz-Laskowice", "Oława"],
                "Polkowicki" => ["Chocianów", "Gaworzyce", "Grębocice", "Polkowice", "Przemków", "Radwanice"],
                "Strzeliński" => ["Borów", "Kondratowice", "Przeworno", "Strzelin", "Wiązów"],
                "Średzki" => ["Kostomłoty", "Malczyce", "Miękinia", "Udanin", "Środa Śląska"],
                "Świdnicki" => ["Dobromierz", "Jaworzyna Śląska", "Marcinowice", "Strzegom", "Świdnica", "Świebodzice", "Żarów"],
                "Trzebnicki" => ["Oborniki Śląskie", "Prusice", "Trzebnica", "Wisznia Mała", "Zawonia", "Żmigród"],
                "Wałbrzyski" => ["Boguszów-Gorce", "Czarny Bór", "Głuszyca", "Jedlina-Zdrój", "Mieroszów", "Stare Bogaczowice", "Szczawno-Zdrój", "Walim"],
                "Wołowski" => ["Brzeg Dolny", "Wińsko", "Wołów"],
                "Wrocławski" => ["Czernica", "Długołęka", "Jordanów Śląski", "Kobierzyce", "Kąty Wrocławskie", "Mietków", "Siechnice", "Sobótka", "Żórawina"],
                "Ząbkowicki" => ["Bardo", "Ciepłowody", "Kamieniec Ząbkowicki", "Stoszowice", "Ziębice", "Ząbkowice Śląskie", "Złoty Stok"],
                "Zgorzelecki" => ["Bogatynia", "Pieńsk", "Sulików", "Węgliniec", "Zawidów", "Zgorzelec"],
                "Złotoryjski" => ["Pielgrzymka", "Wojcieszów", "Zagrodno", "Złotoryja", "Świerzawa"],
                "Jelenia Góra" => ["Jelenia Góra"],
                "Legnica" => ["Legnica"],
                "Wrocław" => ["Wrocław"],
                "Wałbrzych" => ["Wałbrzych"],
            ],
            "Kujawsko-Pomorskie" => [
                "Aleksandrowski" => ["Aleksandrów Kujawski", "Bądkowo", "Ciechocinek", "Koneck", "Nieszawa", "Raciążek", "Waganiec", "Zakrzewo"],
                "Brodnicki" => ["Bartniczka", "Bobrowo", "Brodnica", "Brzozie", "Górzno", "Jabłonowo Pomorskie", "Osiek", "Zbiczno", "Świedziebnia"],
                "Bydgoski" => ["Białe Błota", "Dobrcz", "Dąbrowa Chełmińska", "Koronowo", "Nowa Wieś Wielka", "Osielsko", "Sicienko", "Solec Kujawski"],
                "Chełmiński" => ["Chełmno", "Kijewo Królewskie", "Lisewo", "Papowo Biskupie", "Stolno", "Unisław"],
                "Golubsko-Dobrzyński" => ["Ciechocin", "Golub-Dobrzyń", "Kowalewo Pomorskie", "Radomin", "Zbójno"],
                "Grudziądzki" => ["Grudziądz", "Gruta", "Radzyń Chełmiński", "Rogóźno", "Łasin", "Świecie Nad Osą"],
                "Inowrocławski" => ["Dąbrowa Biskupia", "Gniewkowo", "Inowrocław", "Janikowo", "Kruszwica", "Pakość", "Rojewo", "Złotniki Kujawskie"],
                "Lipnowski" => ["Bobrowniki", "Chrostkowo", "Dobrzyń Nad Wisłą", "Kikół", "Lipno", "Skępe", "Tłuchowo", "Wielgie"],
                "Mogileński" => ["Dąbrowa", "Jeziora Wielkie", "Mogilno", "Strzelno"],
                "Nakielski" => ["Kcynia", "Mrocza", "Nakło Nad Notecią", "Sadki", "Szubin"],
                "Radziejowski" => ["Bytoń", "Dobre", "Osięciny", "Piotrków Kujawski", "Radziejów", "Topólka"],
                "Rypiński" => ["Brzuze", "Rogowo", "Rypin", "Skrwilno", "Wąpielsk"],
                "Sępoleński" => ["Kamień Krajeński", "Sośno", "Sępólno Krajeńskie", "Więcbork"],
                "Świecki" => ["Bukowiec", "Dragacz", "Drzycim", "Jeżewo", "Lniano", "Nowe", "Osie", "Pruszcz", "Warlubie", "Świecie", "Świekatowo"],
                "Toruński" => ["Chełmża", "Czernikowo", "Lubicz", "Obrowo", "Wielka Nieszawka", "Zławieś Wielka", "Łubianka", "Łysomice"],
                "Tucholski" => ["Cekcyn", "Gostycyn", "Kęsowo", "Lubiewo", "Tuchola", "Śliwice"],
                "Wąbrzeski" => ["Dębowa Łąka", "Książki", "Płużnica", "Ryńsk", "Wąbrzeźno"],
                "Włocławski" => ["Baruchowo", "Boniewo", "Brześć Kujawski", "Choceń", "Chodecz", "Fabianki", "Izbica Kujawska", "Kowal", "Lubanie", "Lubień Kujawski", "Lubraniec", "Włocławek"],
                "Żniński" => ["Barcin", "Gąsawa", "Janowiec Wielkopolski", "Rogowo", "Łabiszyn", "Żnin"],
                "Bydgoszcz" => ["Bydgoszcz"],
                "Grudziądz" => ["Grudziądz"],
                "Toruń" => ["Toruń"],
                "Włocławek" => ["Włocławek"],
            ],
            "Lubelskie" => [
                "Bialski" => ["Biała Podlaska", "Drelów", "Janów Podlaski", "Kodeń", "Konstantynów", "Leśna Podlaska", "Międzyrzec Podlaski", "Piszczac", "Rokitno", "Rossosz", "Sosnówka", "Sławatycze", "Terespol", "Tuczna", "Wisznice", "Zalesie", "Łomazy"],
                "Biłgorajski" => ["Aleksandrów", "Biszcza", "Biłgoraj", "Frampol", "Goraj", "Józefów", "Księżpol", "Obsza", "Potok Górny", "Tarnogród", "Tereszpol", "Turobin", "Łukowa"],
                "Chełmski" => ["Białopole", "Chełm", "Dorohusk", "Dubienka", "Kamień", "Leśniowice", "Rejowiec", "Rejowiec Fabryczny", "Ruda-Huta", "Sawin", "Siedliszcze", "Wierzbica", "Wojsławice", "Żmudź"],
                "Hrubieszowski" => ["Dołhobyczów", "Horodło", "Hrubieszów", "Mircze", "Trzeszczany", "Uchanie", "Werbkowice"],
                "Janowski" => ["Batorz", "Chrzanów", "Dzwola", "Godziszów", "Janów Lubelski", "Modliborzyce", "Potok Wielki"],
                "Krasnostawski" => ["Fajsławice", "Gorzków", "Izbica", "Krasnystaw", "Kraśniczyn", "Rudnik", "Siennica Różana", "Łopiennik Górny", "Żółkiewka"],
                "Kraśnicki" => ["Annopol", "Dzierzkowice", "Gościeradów", "Kraśnik", "Szastarka", "Trzydnik Duży", "Urzędów", "Wilkołaz", "Zakrzówek"],
                "Lubartowski" => ["Abramów", "Firlej", "Jeziorzany", "Kamionka", "Kock", "Lubartów", "Michów", "Niedźwiada", "Ostrów Lubelski", "Ostrówek", "Serniki", "Uścimów"],
                "Lubelski" => ["Bełżyce", "Borzechów", "Bychawa", "Garbów", "Głusk", "Jabłonna", "Jastków", "Konopnica", "Krzczonów", "Niedrzwica Duża", "Niemce", "Strzyżewice", "Wojciechów", "Wysokie", "Wólka", "Zakrzew"],
                "Łęczyński" => ["Cyców", "Ludwin", "Milejów", "Puchaczów", "Spiczyn", "Łęczna"],
                "Łukowski" => ["Adamów", "Krzywda", "Serokomla", "Stanin", "Stoczek Łukowski", "Trzebieszów", "Wojcieszków", "Wola Mysłowska", "Łuków"],
                "Opolski" => ["Chodel", "Józefów Nad Wisłą", "Karczmiska", "Opole Lubelskie", "Poniatowa", "Wilków", "Łaziska"],
                "Parczewski" => ["Dębowa Kłoda", "Jabłoń", "Milanów", "Parczew", "Podedwórze", "Siemień", "Sosnowica"],
                "Puławski" => ["Baranów", "Janowiec", "Kazimierz Dolny", "Końskowola", "Kurów", "Markuszów", "Nałęczów", "Puławy", "Wąwolnica", "Żyrzyn"],
                "Radzyński" => ["Borki", "Czemierniki", "Komarówka Podlaska", "Kąkolewnica", "Radzyń Podlaski", "Ulan-Majorat", "Wohyń"],
                "Rycki" => ["Dęblin", "Kłoczew", "Nowodwór", "Ryki", "Stężyca", "Ułęż"],
                "Świdnicki" => ["Mełgiew", "Piaski", "Rybczewice", "Trawniki", "Świdnik"],
                "Tomaszowski" => ["Bełżec", "Jarczów", "Krynice", "Lubycza Królewska", "Rachanie", "Susiec", "Tarnawatka", "Telatyn", "Tomaszów Lubelski", "Tyszowce", "Ulhówek"],
                "Włodawski" => ["Hanna", "Hańsk", "Stary Brus", "Urszulin", "Wola Uhruska", "Wyryki", "Włodawa"],
                "Zamojski" => ["Adamów", "Grabowiec", "Komarów-Osada", "Krasnobród", "Miączyn", "Nielisz", "Radecznica", "Sitno", "Skierbieszów", "Stary Zamość", "Sułów", "Szczebrzeszyn", "Zamość", "Zwierzyniec", "Łabunie"],
                "Biała Podlaska" => ["Biała Podlaska"],
                "Chełm" => ["Chełm"],
                "Lublin" => ["Lublin"],
                "Zamość" => ["Zamość"],
            ],
            "Lubuskie" => [
                "Gorzowski" => ["Bogdaniec", "Deszczno", "Kostrzyn Nad Odrą", "Kłodawa", "Lubiszyn", "Santok", "Witnica"],
                "Krośnieński" => ["Bobrowice", "Bytnica", "Dąbie", "Gubin", "Krosno Odrzańskie", "Maszewo"],
                "Międzyrzecki" => ["Bledzew", "Międzyrzecz", "Przytoczna", "Pszczew", "Skwierzyna", "Trzciel"],
                "Nowosolski" => ["Bytom Odrzański", "Kolsko", "Kożuchów", "Nowa Sól", "Nowe Miasteczko", "Otyń", "Siedlisko"],
                "Słubicki" => ["Cybinka", "Górzyca", "Ośno Lubuskie", "Rzepin", "Słubice"],
                "Strzelecko-Drezdenecki" => ["Dobiegniew", "Drezdenko", "Stare Kurowo", "Strzelce Krajeńskie", "Zwierzyn"],
                "Sulęciński" => ["Krzeszyce", "Lubniewice", "Sulęcin", "Słońsk", "Torzym"],
                "Świebodziński" => ["Lubrza", "Skąpe", "Szczaniec", "Zbąszynek", "Łagów", "Świebodzin"],
                "Zielonogórski" => ["Babimost", "Bojadła", "Czerwieńsk", "Kargowa", "Nowogród Bobrzański", "Sulechów", "Trzebiechów", "Zabór", "Świdnica"],
                "Żagański" => ["Brzeźnica", "Gozdnica", "Iłowa", "Małomice", "Niegosławice", "Szprotawa", "Wymiarki", "Żagań"],
                "Żarski" => ["Brody", "Jasień", "Lipinki Łużyckie", "Lubsko", "Przewóz", "Trzebiel", "Tuplice", "Łęknica", "Żary"],
                "Wschowski" => ["Szlichtyngowa", "Sława", "Wschowa"],
                "Gorzów Wielkopolski" => ["Gorzów Wielkopolski"],
                "Zielona Góra" => ["Zielona Góra"],
            ],
            "Łódzkie" => [
                "Bełchatowski" => ["Bełchatów", "Drużbice", "Kleszczów", "Kluki", "Rusiec", "Szczerców", "Zelów"],
                "Kutnowski" => ["Bedlno", "Dąbrowice", "Krośniewice", "Krzyżanów", "Kutno", "Nowe Ostrowy", "Oporów", "Strzelce", "Łanięta", "Żychlin"],
                "Łaski" => ["Buczek", "Sędziejowice", "Widawa", "Wodzierady", "Łask"],
                "Łęczycki" => ["Daszyna", "Grabów", "Góra Świętej Małgorzaty", "Piątek", "Witonia", "Łęczyca", "Świnice Warckie"],
                "Łowicki" => ["Bielawy", "Chąśno", "Domaniewice", "Kiernozia", "Kocierzew Południowy", "Nieborów", "Zduny", "Łowicz", "Łyszkowice"],
                "Łódzki Wschodni" => ["Andrespol", "Brójce", "Koluszki", "Nowosolna", "Rzgów", "Tuszyn"],
                "Opoczyński" => ["Białaczów", "Drzewica", "Mniszków", "Opoczno", "Paradyż", "Poświętne", "Sławno", "Żarnów"],
                "Pabianicki" => ["Dobroń", "Dłutów", "Konstantynów Łódzki", "Ksawerów", "Lutomiersk", "Pabianice"],
                "Pajęczański" => ["Działoszyn", "Kiełczygłów", "Nowa Brzeźnica", "Pajęczno", "Rząśnia", "Siemkowice", "Strzelce Wielkie", "Sulmierzyce"],
                "Piotrkowski" => ["Aleksandrów", "Czarnocin", "Gorzkowice", "Grabica", "Moszczenica", "Rozprza", "Ręczno", "Sulejów", "Wola Krzysztoporska", "Wolbórz", "Łeki Szlacheckie"],
                "Poddębicki" => ["Dalików", "Poddębice", "Pęczniew", "Uniejów", "Wartkowice", "Zadzim"],
                "Radomszczański" => ["Dobryszyce", "Gidle", "Gomunice", "Kamieńsk", "Kobiele Wielkie", "Kodrąb", "Lgota Wielka", "Masłowice", "Przedbórz", "Radomsko", "Wielgomłyny", "Ładzice", "Żytno"],
                "Rawski" => ["Biała Rawska", "Cielądz", "Rawa Mazowiecka", "Regnów", "Sadkowice"],
                "Sieradzki" => ["Brzeźnio", "Brąszewice", "Burzenin", "Błaszki", "Goszczanów", "Klonowa", "Sieradz", "Warta", "Wróblew", "Złoczew"],
                "Skierniewicki" => ["Bolimów", "Godzianów", "Głuchów", "Kowiesy", "Lipce Reymontowskie", "Maków", "Nowy Kawęczyn", "Skierniewice", "Słupia"],
                "Tomaszowski" => ["Budziszewice", "Będków", "Czerniewice", "Inowłódz", "Lubochnia", "Rokiciny", "Rzeczyca", "Tomaszów Mazowiecki", "Ujazd", "Żelechlinek"],
                "Wieluński" => ["Biała", "Czarnożyły", "Konopnica", "Mokrsko", "Osjaków", "Ostrówek", "Pątnów", "Skomlin", "Wieluń", "Wierzchlas"],
                "Wieruszowski" => ["Bolesławiec", "Czastary", "Galewice", "Lututów", "Sokolniki", "Wieruszów", "Łubnice"],
                "Zduńskowolski" => ["Szadek", "Zapolice", "Zduńska Wola"],
                "Zgierski" => ["Aleksandrów Łódzki", "Głowno", "Ozorków", "Parzęczew", "Stryków", "Zgierz"],
                "Brzeziński" => ["Brzeziny", "Dmosin", "Jeżów", "Rogów"],
                "Łódź" => ["Łódź"],
                "Piotrków Trybunalski" => ["Piotrków Trybunalski"],
                "Skierniewice" => ["Skierniewice"],
            ],
            "Małopolskie" => [
                "Bocheński" => ["Bochnia", "Drwinia", "Lipnica Murowana", "Nowy Wiśnicz", "Rzezawa", "Trzciana", "Łapanów", "Żegocina"],
                "Brzeski" => ["Borzęcin", "Brzesko", "Czchów", "Dębno", "Gnojnik", "Iwkowa", "Szczurowa"],
                "Chrzanowski" => ["Alwernia", "Babice", "Chrzanów", "Libiąż", "Trzebinia"],
                "Dąbrowski" => ["Bolesław", "Dąbrowa Tarnowska", "Gręboszów", "Mędrzechów", "Olesno", "Radgoszcz", "Szczucin"],
                "Gorlicki" => ["Biecz", "Bobowa", "Gorlice", "Lipinki", "Moszczenica", "Ropa", "Sękowa", "Uście Gorlickie", "Łużna"],
                "Krakowski" => ["Czernichów", "Igołomia-Wawrzeńczyce", "Iwanowice", "Jerzmanowice-Przeginia", "Kocmyrzów-Luborzyca", "Krzeszowice", "Liszki", "Michałowice", "Mogilany", "Skawina", "Skała", "Sułoszowa", "Słomniki", "Wielka Wieś", "Zabierzów", "Zielonki", "Świątniki Górne"],
                "Limanowski" => ["Dobra", "Jodłownik", "Kamienica", "Laskowa", "Limanowa", "Mszana Dolna", "Niedźwiedź", "Szczawa", "Słopnice", "Tymbark", "Łukowica"],
                "Miechowski" => ["Charsznica", "Gołcza", "Kozłów", "Książ Wielki", "Miechów", "Racławice", "Słaboszów"],
                "Myślenicki" => ["Dobczyce", "Lubień", "Myślenice", "Pcim", "Raciechowice", "Siepraw", "Sułkowice", "Tokarnia", "Wiśniowa"],
                "Nowosądecki" => ["Chełmiec", "Grybów", "Gródek Nad Dunajcem", "Kamionka Wielka", "Korzenna", "Krynica-Zdrój", "Muszyna", "Nawojowa", "Piwniczna-Zdrój", "Podegrodzie", "Rytro", "Stary Sącz", "Łabowa", "Łososina Dolna", "Łącko"],
                "Nowotarski" => ["Czarny Dunajec", "Czorsztyn", "Jabłonka", "Krościenko Nad Dunajcem", "Lipnica Wielka", "Nowy Targ", "Ochotnica Dolna", "Raba Wyżna", "Rabka-Zdrój", "Spytkowice", "Szaflary", "Szczawnica", "Łapsze Niżne"],
                "Olkuski" => ["Bolesław", "Bukowno", "Klucze", "Olkusz", "Trzyciąż", "Wolbrom"],
                "Oświęcimski" => ["Brzeszcze", "Chełmek", "Kęty", "Osiek", "Oświęcim", "Polanka Wielka", "Przeciszów", "Zator"],
                "Proszowicki" => ["Koniusza", "Koszyce", "Nowe Brzesko", "Pałecznica", "Proszowice", "Radziemice"],
                "Suski" => ["Budzów", "Bystra-Sidzina", "Jordanów", "Maków Podhalański", "Stryszawa", "Sucha Beskidzka", "Zawoja", "Zembrzyce"],
                "Tarnowski" => ["Ciężkowice", "Gromnik", "Lisia Góra", "Pleśna", "Radłów", "Ryglice", "Rzepiennik Strzyżewski", "Skrzyszów", "Szerzyny", "Tarnów", "Tuchów", "Wierzchosławice", "Wietrzychowice", "Wojnicz", "Zakliczyn", "Żabno"],
                "Tatrzański" => ["Biały Dunajec", "Bukowina Tatrzańska", "Kościelisko", "Poronin", "Zakopane"],
                "Wadowicki" => ["Andrychów", "Brzeźnica", "Kalwaria Zebrzydowska", "Lanckorona", "Mucharz", "Spytkowice", "Stryszów", "Tomice", "Wadowice", "Wieprz"],
                "Wielicki" => ["Biskupice", "Gdów", "Kłaj", "Niepołomice", "Wieliczka"],
                "Kraków" => ["Kraków"],
                "Nowy Sącz" => ["Nowy Sącz"],
                "Tarnów" => ["Tarnów"],
            ],
            "Mazowieckie" => [
                "Białobrzeski" => ["Białobrzegi", "Promna", "Radzanów", "Stara Błotnica", "Stromiec", "Wyśmierzyce"],
                "Ciechanowski" => ["Ciechanów", "Glinojeck", "Gołymin-Ośrodek", "Grudusk", "Ojrzeń", "Opinogóra Górna", "Regimin", "Sońsk"],
                "Garwoliński" => ["Borowie", "Garwolin", "Górzno", "Maciejowice", "Miastków Kościelny", "Parysów", "Pilawa", "Sobolew", "Trojanów", "Wilga", "Łaskarzew", "Żelechów"],
                "Gostyniński" => ["Gostynin", "Pacyna", "Sanniki", "Szczawin Kościelny"],
                "Grodziski" => ["Baranów", "Grodzisk Mazowiecki", "Jaktorów", "Milanówek", "Podkowa Leśna", "Żabia Wola"],
                "Grójecki" => ["Belsk Duży", "Błędów", "Chynów", "Goszczyn", "Grójec", "Jasieniec", "Mogielnica", "Nowe Miasto Nad Pilicą", "Pniewy", "Warka"],
                "Kozienicki" => ["Garbatka-Letnisko", "Gniewoszów", "Grabów Nad Pilicą", "Głowaczów", "Kozienice", "Magnuszew", "Sieciechów"],
                "Legionowski" => ["Jabłonna", "Legionowo", "Nieporęt", "Serock", "Wieliszew"],
                "Lipski" => ["Chotcza", "Ciepielów", "Lipsko", "Rzeczniów", "Sienno", "Solec Nad Wisłą"],
                "Łosicki" => ["Huszlew", "Olszanka", "Platerów", "Sarnaki", "Stara Kornica", "Łosice"],
                "Makowski" => ["Czerwonka", "Karniewo", "Krasnosielc", "Maków Mazowiecki", "Młynarze", "Płoniawy-Bramura", "Rzewnie", "Różan", "Sypniewo", "Szelków"],
                "Miński" => ["Cegłów", "Dobre", "Dębe Wielkie", "Halinów", "Jakubów", "Kałuszyn", "Latowicz", "Mińsk Mazowiecki", "Mrozy", "Siennica", "Stanisławów", "Sulejówek"],
                "Mławski" => ["Dzierzgowo", "Lipowiec Kościelny", "Mława", "Radzanów", "Strzegowo", "Stupsk", "Szreńsk", "Szydłowo", "Wieczfnia Kościelna", "Wiśniewo"],
                "Nowodworski" => ["Czosnów", "Leoncin", "Nasielsk", "Nowy Dwór Mazowiecki", "Pomiechówek", "Zakroczym"],
                "Ostrołęcki" => ["Baranowo", "Czarnia", "Czerwin", "Goworowo", "Kadzidło", "Lelis", "Myszyniec", "Olszewo-Borki", "Rzekuń", "Troszyn", "Łyse"],
                "Ostrowski" => ["Andrzejewo", "Boguty-Pianki", "Brok", "Małkinia Górna", "Nur", "Ostrów Mazowiecka", "Stary Lubotyń", "Szulborze Wielkie", "Wąsewo", "Zaręby Kościelne"],
                "Otwocki" => ["Celestynów", "Józefów", "Karczew", "Kołbiel", "Osieck", "Otwock", "Sobienie-Jeziory", "Wiązowna"],
                "Piaseczyński" => ["Góra Kalwaria", "Konstancin-Jeziorna", "Lesznowola", "Piaseczno", "Prażmów", "Tarczyn"],
                "Płocki" => ["Bielsk", "Bodzanów", "Brudzeń Duży", "Bulkowo", "Drobin", "Gąbin", "Mała Wieś", "Nowy Duninów", "Radzanowo", "Stara Biała", "Staroźreby", "Słubice", "Słupno", "Wyszogród", "Łąck"],
                "Płoński" => ["Baboszewo", "Czerwińsk Nad Wisłą", "Dzierzążnia", "Joniec", "Naruszewo", "Nowe Miasto", "Płońsk", "Raciąż", "Sochocin", "Załuski"],
                "Pruszkowski" => ["Brwinów", "Michałowice", "Nadarzyn", "Piastów", "Pruszków", "Raszyn"],
                "Przasnyski" => ["Chorzele", "Czernice Borowe", "Jednorożec", "Krasne", "Krzynowłoga Mała", "Przasnysz"],
                "Przysuski" => ["Borkowice", "Gielniów", "Klwów", "Odrzywół", "Potworów", "Przysucha", "Rusinów", "Wieniawa"],
                "Pułtuski" => ["Gzy", "Obryte", "Pokrzywnica", "Pułtusk", "Winnica", "Zatory", "Świercze"],
                "Radomski" => ["Gózd", "Iłża", "Jastrzębia", "Jedlińsk", "Jedlnia-Letnisko", "Kowala", "Pionki", "Przytyk", "Skaryszew", "Wierzbica", "Wolanów", "Zakrzew"],
                "Siedlecki" => ["Domanice", "Korczew", "Kotuń", "Mokobody", "Mordy", "Paprotnia", "Przesmyki", "Siedlce", "Skórzec", "Suchożebry", "Wiśniew", "Wodynie", "Zbuczyn"],
                "Sierpecki" => ["Gozdowo", "Mochowo", "Rościszewo", "Sierpc", "Szczutowo", "Zawidz"],
                "Sochaczewski" => ["Brochów", "Iłów", "Młodzieszyn", "Nowa Sucha", "Rybno", "Sochaczew", "Teresin"],
                "Sokołowski" => ["Bielany", "Ceranów", "Jabłonna Lacka", "Kosów Lacki", "Repki", "Sabnie", "Sokołów Podlaski", "Sterdyń"],
                "Szydłowiecki" => ["Chlewiska", "Jastrząb", "Mirów", "Orońsko", "Szydłowiec"],
                "Warszawski Zachodni" => ["Błonie", "Izabelin", "Kampinos", "Leszno", "Ożarów Mazowiecki", "Stare Babice", "Łomianki"],
                "Węgrowski" => ["Grębków", "Korytnica", "Liw", "Miedzna", "Sadowne", "Stoczek", "Wierzbno", "Węgrów", "Łochów"],
                "Wołomiński" => ["Dąbrówka", "Jadów", "Klembów", "Kobyłka", "Marki", "Poświętne", "Radzymin", "Strachówka", "Tłuszcz", "Wołomin", "Zielonka", "Ząbki"],
                "Wyszkowski" => ["Brańszczyk", "Długosiodło", "Rząśnik", "Somianka", "Wyszków", "Zabrodzie"],
                "Zwoleński" => ["Kazanów", "Policzna", "Przyłęk", "Tczów", "Zwoleń"],
                "Żuromiński" => ["Bieżuń", "Kuczbork-Osada", "Lubowidz", "Lutocin", "Siemiątkowo", "Żuromin"],
                "Żyrardowski" => ["Mszczonów", "Puszcza Mariańska", "Radziejowice", "Wiskitki", "Żyrardów"],
                "Ostrołęka" => ["Ostrołęka"],
                "Płock" => ["Płock"],
                "Radom" => ["Radom"],
                "Siedlce" => ["Siedlce"],
                "Warszawa" => ["Warszawa"],
            ],
            "Opolskie" => [
                "Brzeski" => ["Brzeg", "Grodków", "Lewin Brzeski", "Lubsza", "Olszanka", "Skarbimierz"],
                "Głubczycki" => ["Baborów", "Branice", "Głubczyce", "Kietrz"],
                "Kędzierzyńsko-Kozielski" => ["Bierawa", "Cisek", "Kędzierzyn-Koźle", "Pawłowiczki", "Polska Cerekiew", "Reńska Wieś"],
                "Kluczborski" => ["Byczyna", "Kluczbork", "Lasowice Wielkie", "Wołczyn"],
                "Krapkowicki" => ["Gogolin", "Krapkowice", "Strzeleczki", "Walce", "Zdzieszowice"],
                "Namysłowski" => ["Domaszowice", "Namysłów", "Pokój", "Wilków", "Świerczów"],
                "Nyski" => ["Głuchołazy", "Kamiennik", "Korfantów", "Nysa", "Otmuchów", "Paczków", "Pakosławice", "Skoroszyce", "Łambinowice"],
                "Oleski" => ["Dobrodzień", "Gorzów Śląski", "Olesno", "Praszka", "Radłów", "Rudniki", "Zębowice"],
                "Opolski" => ["Chrząstowice", "Dobrzeń Wielki", "Dąbrowa", "Komprachcice", "Murów", "Niemodlin", "Ozimek", "Popielów", "Prószków", "Tarnów Opolski", "Turawa", "Tułowice", "Łubniany"],
                "Prudnicki" => ["Biała", "Głogówek", "Lubrza", "Prudnik"],
                "Strzelecki" => ["Izbicko", "Jemielnica", "Kolonowskie", "Leśnica", "Strzelce Opolskie", "Ujazd", "Zawadzkie"],
                "Opole" => ["Opole"],
            ],
            "Podkarpackie" => [
                "Bieszczadzki" => ["Czarna", "Lutowiska", "Ustrzyki Dolne"],
                "Brzozowski" => ["Brzozów", "Domaradz", "Dydnia", "Haczów", "Jasienica Rosielna", "Nozdrzec"],
                "Dębicki" => ["Brzostek", "Czarna", "Dębica", "Jodłowa", "Pilzno", "Żyraków"],
                "Jarosławski" => ["Chłopice", "Jarosław", "Laszki", "Pawłosiów", "Pruchnik", "Radymno", "Rokietnica", "Roźwienica", "Wiązownica"],
                "Jasielski" => ["Brzyska", "Dębowiec", "Jasło", "Kołaczyce", "Krempna", "Nowy Żmigród", "Osiek Jasielski", "Skołyszyn", "Tarnowiec"],
                "Kolbuszowski" => ["Cmolas", "Dzikowiec", "Kolbuszowa", "Majdan Królewski", "Niwiska", "Raniżów"],
                "Krośnieński" => ["Chorkówka", "Dukla", "Iwonicz-Zdrój", "Jaśliska", "Jedlicze", "Korczyna", "Krościenko Wyżne", "Miejsce Piastowe", "Rymanów", "Wojaszówka"],
                "Leżajski" => ["Grodzisko Dolne", "Kuryłówka", "Leżajsk", "Nowa Sarzyna"],
                "Lubaczowski" => ["Cieszanów", "Horyniec-Zdrój", "Lubaczów", "Narol", "Oleszyce", "Stary Dzików", "Wielkie Oczy"],
                "Łańcucki" => ["Białobrzegi", "Czarna", "Markowa", "Rakszawa", "Łańcut", "Żołynia"],
                "Mielecki" => ["Borowa", "Czermin", "Gawłuszowice", "Mielec", "Padew Narodowa", "Przecław", "Radomyśl Wielki", "Tuszów Narodowy", "Wadowice Górne"],
                "Niżański" => ["Harasiuki", "Jarocin", "Jeżowe", "Krzeszów", "Nisko", "Rudnik Nad Sanem", "Ulanów"],
                "Przemyski" => ["Bircza", "Dubiecko", "Fredropol", "Krasiczyn", "Krzywcza", "Medyka", "Orły", "Przemyśl", "Stubno", "Żurawica"],
                "Przeworski" => ["Adamówka", "Gać", "Jawornik Polski", "Kańczuga", "Przeworsk", "Sieniawa", "Tryńcza", "Zarzecze"],
                "Ropczycko-Sędziszowski" => ["Iwierzyce", "Ostrów", "Ropczyce", "Sędziszów Małopolski", "Wielopole Skrzyńskie"],
                "Rzeszowski" => ["Boguchwała", "Błażowa", "Chmielnik", "Dynów", "Głogów Małopolski", "Hyżne", "Kamień", "Krasne", "Lubenia", "Sokołów Małopolski", "Trzebownisko", "Tyczyn", "Świlcza"],
                "Sanocki" => ["Besko", "Bukowsko", "Komańcza", "Sanok", "Tyrawa Wołoska", "Zagórz", "Zarszyn"],
                "Stalowowolski" => ["Bojanów", "Pysznica", "Radomyśl Nad Sanem", "Stalowa Wola", "Zaklików", "Zaleszany"],
                "Strzyżowski" => ["Czudec", "Frysztak", "Niebylec", "Strzyżów", "Wiśniowa"],
                "Tarnobrzeski" => ["Baranów Sandomierski", "Gorzyce", "Grębów", "Nowa Dęba"],
                "Leski" => ["Baligród", "Cisna", "Lesko", "Olszanica", "Solina"],
                "Krosno" => ["Krosno"],
                "Przemyśl" => ["Przemyśl"],
                "Rzeszów" => ["Rzeszów"],
                "Tarnobrzeg" => ["Tarnobrzeg"],
            ],
            "Podlaskie" => [
                "Augustowski" => ["Augustów", "Bargłów Kościelny", "Lipsk", "Nowinka", "Płaska", "Sztabin"],
                "Białostocki" => ["Choroszcz", "Czarna Białostocka", "Dobrzyniewo Duże", "Grabówka", "Gródek", "Juchnowiec Kościelny", "Michałowo", "Poświętne", "Supraśl", "Suraż", "Turośń Kościelna", "Tykocin", "Wasilków", "Zabłudów", "Zawady", "Łapy"],
                "Bielski" => ["Bielsk Podlaski", "Boćki", "Brańsk", "Orla", "Rudka", "Wyszki"],
                "Grajewski" => ["Grajewo", "Radziłów", "Rajgród", "Szczuczyn", "Wąsosz"],
                "Hajnowski" => ["Białowieża", "Czeremcha", "Czyże", "Dubicze Cerkiewne", "Hajnówka", "Kleszczele", "Narew", "Narewka"],
                "Kolneński" => ["Grabowo", "Kolno", "Mały Płock", "Stawiski", "Turośl"],
                "Łomżyński" => ["Jedwabne", "Miastkowo", "Nowogród", "Piątnica", "Przytuły", "Wizna", "Zbójna", "Łomża", "Śniadowo"],
                "Moniecki" => ["Goniądz", "Jasionówka", "Jaświły", "Knyszyn", "Krypno", "Mońki", "Trzcianne"],
                "Sejneński" => ["Giby", "Krasnopol", "Puńsk", "Sejny"],
                "Siemiatycki" => ["Drohiczyn", "Dziadkowice", "Grodzisk", "Mielnik", "Milejczyce", "Nurzec-Stacja", "Perlejewo", "Siemiatycze"],
                "Sokólski" => ["Dąbrowa Białostocka", "Janów", "Korycin", "Krynki", "Kuźnica", "Nowy Dwór", "Sidra", "Sokółka", "Suchowola", "Szudziałowo"],
                "Suwalski" => ["Bakałarzewo", "Filipów", "Jeleniewo", "Przerośl", "Raczki", "Rutka-Tartak", "Suwałki", "Szypliszki", "Wiżajny"],
                "Wysokomazowiecki" => ["Ciechanowiec", "Czyżew", "Klukowo", "Kobylin-Borzymy", "Kulesze Kościelne", "Nowe Piekuty", "Sokoły", "Szepietowo", "Wysokie Mazowieckie"],
                "Zambrowski" => ["Kołaki Kościelne", "Rutki", "Szumowo", "Zambrów"],
                "Białystok" => ["Białystok"],
                "Łomża" => ["Łomża"],
                "Suwałki" => ["Suwałki"],
            ],
            "Pomorskie" => [
                "Bytowski" => ["Borzytuchom", "Bytów", "Czarna Dąbrówka", "Kołczygłowy", "Lipnica", "Miastko", "Parchowo", "Studzienice", "Trzebielino", "Tuchomie"],
                "Chojnicki" => ["Brusy", "Chojnice", "Czersk", "Konarzyny"],
                "Człuchowski" => ["Czarne", "Człuchów", "Debrzno", "Koczała", "Przechlewo", "Rzeczenica"],
                "Gdański" => ["Cedry Wielkie", "Kolbudy", "Pruszcz Gdański", "Przywidz", "Pszczółki", "Suchy Dąb", "Trąbki Wielkie"],
                "Kartuski" => ["Chmielno", "Kartuzy", "Przodkowo", "Sierakowice", "Somonino", "Stężyca", "Sulęczyno", "Żukowo"],
                "Kościerski" => ["Dziemiany", "Karsin", "Kościerzyna", "Liniewo", "Lipusz", "Nowa Karczma", "Stara Kiszewa"],
                "Kwidzyński" => ["Gardeja", "Kwidzyn", "Prabuty", "Ryjewo", "Sadlinki"],
                "Lęborski" => ["Cewice", "Lębork", "Nowa Wieś Lęborska", "Wicko", "Łeba"],
                "Malborski" => ["Lichnowy", "Malbork", "Miłoradz", "Nowy Staw", "Stare Pole"],
                "Nowodworski" => ["Krynica Morska", "Nowy Dwór Gdański", "Ostaszewo", "Stegna", "Sztutowo"],
                "Pucki" => ["Hel", "Jastarnia", "Kosakowo", "Krokowa", "Puck", "Władysławowo"],
                "Słupski" => ["Damnica", "Dębnica Kaszubska", "Główczyce", "Kobylnica", "Kępice", "Potęgowo", "Redzikowo", "Smołdzino", "Ustka"],
                "Starogardzki" => ["Bobowo", "Czarna Woda", "Kaliska", "Lubichowo", "Osieczna", "Osiek", "Skarszewy", "Skórcz", "Smętowo Graniczne", "Starogard Gdański", "Zblewo"],
                "Tczewski" => ["Gniew", "Morzeszczyn", "Pelplin", "Subkowy", "Tczew"],
                "Wejherowski" => ["Choczewo", "Gniewino", "Linia", "Luzino", "Reda", "Rumia", "Szemud", "Wejherowo", "Łęczyce"],
                "Sztumski" => ["Dzierzgoń", "Mikołajki Pomorskie", "Stary Dzierzgoń", "Stary Targ", "Sztum"],
                "Gdańsk" => ["Gdańsk"],
                "Gdynia" => ["Gdynia"],
                "Słupsk" => ["Słupsk"],
                "Sopot" => ["Sopot"],
            ],
            "Śląskie" => [
                "Będziński" => ["Bobrowniki", "Będzin", "Czeladź", "Mierzęcice", "Psary", "Siewierz", "Sławków", "Wojkowice"],
                "Bielski" => ["Bestwina", "Buczkowice", "Czechowice-Dziedzice", "Jasienica", "Jaworze", "Kozy", "Porąbka", "Szczyrk", "Wilamowice", "Wilkowice"],
                "Cieszyński" => ["Brenna", "Chybie", "Cieszyn", "Dębowiec", "Goleszów", "Hażlach", "Istebna", "Skoczów", "Strumień", "Ustroń", "Wisła", "Zebrzydowice"],
                "Częstochowski" => ["Blachownia", "Dąbrowa Zielona", "Janów", "Kamienica Polska", "Koniecpol", "Konopiska", "Kruszyna", "Kłomnice", "Lelów", "Mstów", "Mykanów", "Olsztyn", "Poczesna", "Przyrów", "Rędziny", "Starcza"],
                "Gliwicki" => ["Gierałtowice", "Knurów", "Pilchowice", "Pyskowice", "Rudziniec", "Sośnicowice", "Toszek", "Wielowieś"],
                "Kłobucki" => ["Krzepice", "Kłobuck", "Lipie", "Miedźno", "Opatów", "Panki", "Popów", "Przystajń", "Wręczyca Wielka"],
                "Lubliniecki" => ["Boronów", "Ciasna", "Herby", "Kochanowice", "Koszęcin", "Lubliniec", "Pawonków", "Woźniki"],
                "Mikołowski" => ["Mikołów", "Ornontowice", "Orzesze", "Wyry", "Łaziska Górne"],
                "Myszkowski" => ["Koziegłowy", "Myszków", "Niegowa", "Poraj", "Żarki"],
                "Pszczyński" => ["Goczałkowice-Zdrój", "Kobiór", "Miedźna", "Pawłowice", "Pszczyna", "Suszec"],
                "Raciborski" => ["Kornowac", "Krzanowice", "Krzyżanowice", "Kuźnia Raciborska", "Nędza", "Pietrowice Wielkie", "Racibórz", "Rudnik"],
                "Rybnicki" => ["Czerwionka-Leszczyny", "Gaszowice", "Jejkowice", "Lyski", "Świerklany"],
                "Tarnogórski" => ["Kalety", "Krupski Młyn", "Miasteczko Śląskie", "Ożarowice", "Radzionków", "Tarnowskie Góry", "Tworóg", "Zbrosławice", "Świerklaniec"],
                "Bieruńsko-Lędziński" => ["Bieruń", "Bojszowy", "Chełm Śląski", "Imielin", "Lędziny"],
                "Wodzisławski" => ["Godów", "Gorzyce", "Lubomia", "Marklowice", "Mszana", "Pszów", "Radlin", "Rydułtowy", "Wodzisław Śląski"],
                "Zawierciański" => ["Irządze", "Kroczyce", "Ogrodzieniec", "Pilica", "Poręba", "Szczekociny", "Włodowice", "Zawiercie", "Łazy", "Żarnowiec"],
                "Żywiecki" => ["Czernichów", "Gilowice", "Jeleśnia", "Koszarawa", "Lipowa", "Milówka", "Radziechowy-Wieprz", "Rajcza", "Ujsoły", "Węgierska Górka", "Łodygowice", "Łękawica", "Ślemień", "Świnna", "Żywiec"],
                "Bielsko-Biała" => ["Bielsko-Biała"],
                "Bytom" => ["Bytom"],
                "Chorzów" => ["Chorzów"],
                "Częstochowa" => ["Częstochowa"],
                "Dąbrowa Górnicza" => ["Dąbrowa Górnicza"],
                "Gliwice" => ["Gliwice"],
                "Jastrzębie-Zdrój" => ["Jastrzębie-Zdrój"],
                "Jaworzno" => ["Jaworzno"],
                "Katowice" => ["Katowice"],
                "Mysłowice" => ["Mysłowice"],
                "Piekary Śląskie" => ["Piekary Śląskie"],
                "Ruda Śląska" => ["Ruda Śląska"],
                "Rybnik" => ["Rybnik"],
                "Siemianowice Śląskie" => ["Siemianowice Śląskie"],
                "Sosnowiec" => ["Sosnowiec"],
                "Świętochłowice" => ["Świętochłowice"],
                "Tychy" => ["Tychy"],
                "Zabrze" => ["Zabrze"],
                "Żory" => ["Żory"],
            ],
            "Świętokrzyskie" => [
                "Buski" => ["Busko-Zdrój", "Gnojno", "Nowy Korczyn", "Pacanów", "Solec-Zdrój", "Stopnica", "Tuczępy", "Wiślica"],
                "Jędrzejowski" => ["Imielno", "Jędrzejów", "Małogoszcz", "Nagłowice", "Oksa", "Sobków", "Sędziszów", "Słupia", "Wodzisław"],
                "Kazimierski" => ["Bejsce", "Czarnocin", "Kazimierza Wielka", "Opatowiec", "Skalbmierz"],
                "Kielecki" => ["Bieliny", "Bodzentyn", "Chmielnik", "Chęciny", "Daleszyce", "Górno", "Masłów", "Miedziana Góra", "Mniów", "Morawica", "Nowa Słupia", "Nowiny", "Piekoszów", "Pierzchnica", "Raków", "Strawczyn", "Zagnańsk", "Łagów", "Łopuszno"],
                "Konecki" => ["Fałków", "Gowarczów", "Końskie", "Radoszyce", "Ruda Maleniecka", "Smyków", "Stąporków", "Słupia Konecka"],
                "Opatowski" => ["Baćkowice", "Iwaniska", "Lipnik", "Opatów", "Ożarów", "Sadowie", "Tarłów", "Wojciechowice"],
                "Ostrowiecki" => ["Bałtów", "Bodzechów", "Kunów", "Ostrowiec Świętokrzyski", "Waśniów", "Ćmielów"],
                "Pińczowski" => ["Działoszyce", "Kije", "Michałów", "Pińczów", "Złota"],
                "Sandomierski" => ["Dwikozy", "Klimontów", "Koprzywnica", "Obrazów", "Samborzec", "Sandomierz", "Wilczyce", "Zawichost", "Łoniów"],
                "Skarżyski" => ["Bliżyn", "Skarżysko Kościelne", "Skarżysko-Kamienna", "Suchedniów", "Łączna"],
                "Starachowicki" => ["Brody", "Mirzec", "Pawłów", "Starachowice", "Wąchock"],
                "Staszowski" => ["Bogoria", "Oleśnica", "Osiek", "Połaniec", "Rytwiany", "Staszów", "Szydłów", "Łubnice"],
                "Włoszczowski" => ["Kluczewsko", "Krasocin", "Moskorzew", "Radków", "Secemin", "Włoszczowa"],
                "Kielce" => ["Kielce"],
            ],
            "Warmińsko-Mazurskie" => [
                "Bartoszycki" => ["Bartoszyce", "Bisztynek", "Górowo Iławeckie", "Sępopol"],
                "Braniewski" => ["Braniewo", "Frombork", "Lelkowo", "Pieniężno", "Płoskinia", "Wilczęta"],
                "Działdowski" => ["Działdowo", "Iłowo-Osada", "Lidzbark", "Płośnica", "Rybno"],
                "Elbląski" => ["Elbląg", "Godkowo", "Gronowo Elbląskie", "Markusy", "Milejewo", "Młynary", "Pasłęk", "Rychliki", "Tolkmicko"],
                "Ełcki" => ["Ełk", "Kalinowo", "Prostki", "Stare Juchy"],
                "Giżycki" => ["Giżycko", "Kruklanki", "Miłki", "Ryn", "Wydminy"],
                "Iławski" => ["Iława", "Kisielice", "Lubawa", "Susz", "Zalewo"],
                "Kętrzyński" => ["Barciany", "Korsze", "Kętrzyn", "Reszel", "Srokowo"],
                "Lidzbarski" => ["Kiwity", "Lidzbark Warmiński", "Lubomino", "Orneta"],
                "Mrągowski" => ["Mikołajki", "Mrągowo", "Piecki", "Sorkwity"],
                "Nidzicki" => ["Janowiec Kościelny", "Janowo", "Kozłowo", "Nidzica"],
                "Nowomiejski" => ["Biskupiec", "Bratian", "Grodziczno", "Kurzętnik", "Nowe Miasto Lubawskie"],
                "Olecki" => ["Kowale Oleckie", "Olecko", "Wieliczki", "Świętajno"],
                "Olsztyński" => ["Barczewo", "Biskupiec", "Dobre Miasto", "Dywity", "Gietrzwałd", "Jeziorany", "Jonkowo", "Kolno", "Olsztynek", "Purda", "Stawiguda", "Świątki"],
                "Ostródzki" => ["Dąbrówno", "Grunwald", "Małdyty", "Miłakowo", "Miłomłyn", "Morąg", "Ostróda", "Łukta"],
                "Piski" => ["Biała Piska", "Orzysz", "Pisz", "Ruciane-Nida"],
                "Szczycieński" => ["Dźwierzuty", "Jedwabno", "Pasym", "Rozogi", "Szczytno", "Wielbark", "Świętajno"],
                "Gołdapski" => ["Banie Mazurskie", "Dubeninki", "Gołdap"],
                "Węgorzewski" => ["Budry", "Pozezdrze", "Węgorzewo"],
                "Elbląg" => ["Elbląg"],
                "Olsztyn" => ["Olsztyn"],
            ],
            "Wielkopolskie" => [
                "Chodzieski" => ["Budzyń", "Chodzież", "Margonin", "Szamocin"],
                "Czarnkowsko-Trzcianecki" => ["Czarnków", "Drawsko", "Krzyż Wielkopolski", "Lubasz", "Połajewo", "Trzcianka", "Wieleń"],
                "Gnieźnieński" => ["Czerniejewo", "Gniezno", "Kiszkowo", "Kłecko", "Mieleszyn", "Niechanowo", "Trzemeszno", "Witkowo", "Łubowo"],
                "Gostyński" => ["Borek Wielkopolski", "Gostyń", "Krobia", "Piaski", "Pogorzela", "Poniec", "Pępowo"],
                "Grodziski" => ["Granowo", "Grodzisk Wielkopolski", "Kamieniec", "Rakoniewice", "Wielichowo"],
                "Jarociński" => ["Jaraczewo", "Jarocin", "Kotlin", "Żerków"],
                "Kaliski" => ["Blizanów", "Brzeziny", "Ceków-Kolonia", "Godziesze Wielkie", "Koźminek", "Lisków", "Mycielin", "Opatówek", "Stawiszyn", "Szczytniki", "Żelazków"],
                "Kępiński" => ["Baranów", "Bralin", "Kępno", "Perzów", "Rychtal", "Trzcinica", "Łęka Opatowska"],
                "Kolski" => ["Babiak", "Chodów", "Dąbie", "Grzegorzew", "Koło", "Kościelec", "Kłodawa", "Olszówka", "Osiek Mały", "Przedecz"],
                "Koniński" => ["Golina", "Grodziec", "Kazimierz Biskupi", "Kleczew", "Kramsk", "Krzymów", "Rychwał", "Rzgów", "Skulsk", "Sompolno", "Stare Miasto", "Wierzbinek", "Wilczyn", "Ślesin"],
                "Kościański" => ["Czempiń", "Kościan", "Krzywiń", "Śmigiel"],
                "Krotoszyński" => ["Kobylin", "Koźmin Wielkopolski", "Krotoszyn", "Rozdrażew", "Sulmierzyce", "Zduny"],
                "Leszczyński" => ["Krzemieniewo", "Lipno", "Osieczna", "Rydzyna", "Wijewo", "Włoszakowice", "Święciechowa"],
                "Międzychodzki" => ["Chrzypsko Wielkie", "Kwilcz", "Międzychód", "Sieraków"],
                "Nowotomyski" => ["Kuślin", "Lwówek", "Miedzichowo", "Nowy Tomyśl", "Opalenica", "Zbąszyń"],
                "Obornicki" => ["Oborniki", "Rogoźno", "Ryczywół"],
                "Ostrowski" => ["Nowe Skalmierzyce", "Odolanów", "Ostrów Wielkopolski", "Przygodzice", "Raszków", "Sieroszewice", "Sośnie"],
                "Ostrzeszowski" => ["Czajków", "Doruchów", "Grabów Nad Prosną", "Kobyla Góra", "Kraszewice", "Mikstat", "Ostrzeszów"],
                "Pilski" => ["Białośliwie", "Kaczory", "Miasteczko Krajeńskie", "Piła", "Szydłowo", "Ujście", "Wyrzysk", "Wysoka", "Łobżenica"],
                "Pleszewski" => ["Chocz", "Czermin", "Dobrzyca", "Gizałki", "Gołuchów", "Pleszew"],
                "Poznański" => ["Buk", "Czerwonak", "Dopiewo", "Kleszczewo", "Komorniki", "Kostrzyn", "Kórnik", "Luboń", "Mosina", "Murowana Goślina", "Pobiedziska", "Puszczykowo", "Rokietnica", "Stęszew", "Suchy Las", "Swarzędz", "Tarnowo Podgórne"],
                "Rawicki" => ["Bojanowo", "Jutrosin", "Miejska Górka", "Pakosław", "Rawicz"],
                "Słupecki" => ["Lądek", "Orchowo", "Ostrowite", "Powidz", "Strzałkowo", "Słupca", "Zagórów"],
                "Szamotulski" => ["Duszniki", "Kaźmierz", "Obrzycko", "Ostroróg", "Pniewy", "Szamotuły", "Wronki"],
                "Średzki" => ["Dominowo", "Krzykosy", "Nowe Miasto Nad Wartą", "Zaniemyśl", "Środa Wielkopolska"],
                "Śremski" => ["Brodnica", "Dolsk", "Książ Wielkopolski", "Śrem"],
                "Turecki" => ["Brudzew", "Dobra", "Kawęczyn", "Malanów", "Przykona", "Tuliszków", "Turek", "Władysławów"],
                "Wągrowiecki" => ["Damasławek", "Gołańcz", "Mieścisko", "Skoki", "Wapno", "Wągrowiec"],
                "Wolsztyński" => ["Przemęt", "Siedlec", "Wolsztyn"],
                "Wrzesiński" => ["Kołaczkowo", "Miłosław", "Nekla", "Pyzdry", "Września"],
                "Złotowski" => ["Jastrowie", "Krajenka", "Lipka", "Okonek", "Tarnówka", "Zakrzewo", "Złotów"],
                "Kalisz" => ["Kalisz"],
                "Konin" => ["Konin"],
                "Leszno" => ["Leszno"],
                "Poznań" => ["Poznań"],
            ],
            "Zachodniopomorskie" => [
                "Białogardzki" => ["Białogard", "Karlino", "Tychowo"],
                "Choszczeński" => ["Bierzwnik", "Choszczno", "Drawno", "Krzęcin", "Pełczyce", "Recz"],
                "Drawski" => ["Czaplinek", "Drawsko Pomorskie", "Kalisz Pomorski", "Wierzchowo", "Złocieniec"],
                "Goleniowski" => ["Goleniów", "Maszewo", "Nowogard", "Osina", "Przybiernów", "Stepnica"],
                "Gryficki" => ["Brojce", "Gryfice", "Karnice", "Płoty", "Rewal", "Trzebiatów"],
                "Gryfiński" => ["Banie", "Cedynia", "Chojna", "Gryfino", "Mieszkowice", "Moryń", "Stare Czarnowo", "Trzcińsko-Zdrój", "Widuchowa"],
                "Kamieński" => ["Dziwnów", "Golczewo", "Kamień Pomorski", "Międzyzdroje", "Wolin", "Świerzno"],
                "Kołobrzeski" => ["Dygowo", "Gościno", "Kołobrzeg", "Rymań", "Siemyśl", "Ustronie Morskie"],
                "Koszaliński" => ["Biesiekierz", "Bobolice", "Będzino", "Manowo", "Mielno", "Polanów", "Sianów", "Świeszyno"],
                "Myśliborski" => ["Barlinek", "Boleszkowice", "Dębno", "Myślibórz", "Nowogródek Pomorski"],
                "Policki" => ["Dobra (szczecińska)", "Kołbaskowo", "Nowe Warpno", "Police"],
                "Pyrzycki" => ["Bielice", "Kozielice", "Lipiany", "Przelewice", "Pyrzyce", "Warnice"],
                "Sławieński" => ["Darłowo", "Malechowo", "Postomino", "Sławno"],
                "Stargardzki" => ["Chociwel", "Dobrzany", "Dolice", "Ińsko", "Kobylanka", "Marianowo", "Stara Dąbrowa", "Stargard", "Suchań"],
                "Szczecinecki" => ["Barwice", "Biały Bór", "Borne Sulinowo", "Grzmiąca", "Szczecinek"],
                "Świdwiński" => ["Brzeżno", "Połczyn-Zdrój", "Rąbino", "Sławoborze", "Świdwin"],
                "Wałecki" => ["Człopa", "Mirosławiec", "Tuczno", "Wałcz"],
                "Łobeski" => ["Dobra", "Radowo Małe", "Resko", "Węgorzyno", "Łobez"],
                "Koszalin" => ["Koszalin"],
                "Szczecin" => ["Szczecin"],
                "Świnoujście" => ["Świnoujście"],
            ],
        ];
    }
}
